#!/usr/bin/env python3
"""Setup schema mirror su PostgreSQL (target della traduzione).

Crea l'equivalente PostgreSQL+orafce dello schema Oracle di test:
stesse tabelle/logica, tipi PG, funzioni PL/pgSQL per il package pkg_demo.

Uso: python3 setup_postgres.py
"""
import sys
from pathlib import Path

import psycopg

sys.path.insert(0, str(Path(__file__).parent))
from config import POSTGRES  # noqa: E402

SCHEMA_SQL = r"""
DROP SCHEMA IF EXISTS pkg_demo CASCADE;
DROP TABLE IF EXISTS t_audit, t_log, t_types, t_default_seq, emp, dept CASCADE;
DROP VIEW  IF EXISTS v_high_sal;
DROP FUNCTION IF EXISTS trg_emp_audit_fn() CASCADE;
DROP FUNCTION IF EXISTS f_sal_level(NUMERIC);
DROP SEQUENCE IF EXISTS seq_emp, seq_default;

CREATE TABLE dept (
   deptno  SMALLINT     CONSTRAINT pk_dept PRIMARY KEY,
   dname   VARCHAR(14)  NOT NULL,
   loc     VARCHAR(13)
);

CREATE TABLE emp (
   empno    INT          CONSTRAINT pk_emp PRIMARY KEY,
   ename    VARCHAR(10)  NOT NULL,
   job      VARCHAR(9),
   mgr      INT          REFERENCES emp(empno),
   hiredate DATE         DEFAULT CURRENT_DATE NOT NULL,
   sal      NUMERIC(7,2),
   comm     NUMERIC(7,2),
   deptno   SMALLINT     REFERENCES dept(deptno),
   notes    TEXT,
   foto     BYTEA
);

CREATE INDEX idx_emp_ename ON emp(ename);
CREATE INDEX idx_emp_sal   ON emp(sal);
CREATE INDEX idx_emp_upper ON emp(UPPER(ename));

CREATE TABLE t_types (
   id       INT GENERATED BY DEFAULT AS IDENTITY,
   n_small  SMALLINT,
   n_full   NUMERIC,
   n_dec    NUMERIC(9,2),
   v_var    VARCHAR(50),
   c_fixed  CHAR(5),
   d_date   TIMESTAMP(0),  -- Oracle DATE -> PG timestamp(0): regola ora2pg
   ts       TIMESTAMP(6),
   raw16    BYTEA,
   big_text TEXT,
   big_bin  BYTEA,
   i_day    INTERVAL DAY TO SECOND
);

CREATE TABLE t_log (
   id   BIGINT GENERATED ALWAYS AS IDENTITY,
   ts   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   msg  VARCHAR(400)
);

CREATE TABLE t_audit (
   table_name VARCHAR(30),
   action     VARCHAR(10),
   cnt        NUMERIC DEFAULT 1,
   ts         DATE DEFAULT CURRENT_DATE
);

CREATE SEQUENCE seq_emp    START WITH 1000 INCREMENT BY 10;
CREATE SEQUENCE seq_default START WITH 1;

CREATE TABLE t_default_seq (
   id  INT DEFAULT nextval('seq_default') PRIMARY KEY,
   tag VARCHAR(30)
);

CREATE VIEW v_high_sal AS SELECT empno, ename, sal FROM emp WHERE sal >= 2500;

CREATE FUNCTION f_sal_level(p_sal NUMERIC) RETURNS TEXT AS $$
BEGIN
   RETURN CASE WHEN p_sal >= 3000 THEN 'HIGH'
               WHEN p_sal >= 1500 THEN 'MID' ELSE 'LOW' END;
END;
$$ LANGUAGE plpgsql;

CREATE SCHEMA pkg_demo;

CREATE TABLE pkg_demo.state (k TEXT PRIMARY KEY, v NUMERIC);
INSERT INTO pkg_demo.state VALUES ('g_session_val', 0);

CREATE FUNCTION pkg_demo.set_x(p_val NUMERIC) RETURNS VOID AS $$
   UPDATE pkg_demo.state SET v = p_val WHERE k = 'g_session_val';
$$ LANGUAGE sql;

CREATE FUNCTION pkg_demo.get_x() RETURNS NUMERIC AS $$
   SELECT v FROM pkg_demo.state WHERE k = 'g_session_val';
$$ LANGUAGE sql;

CREATE FUNCTION pkg_demo.get_emp_name(p_empno INT) RETURNS TEXT AS $$
DECLARE l_name TEXT;
BEGIN
   SELECT ename INTO l_name FROM emp WHERE empno = p_empno;
   RETURN l_name;
EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE FUNCTION pkg_demo.log_msg(p_msg TEXT) RETURNS VOID AS $$
   INSERT INTO t_log(msg) VALUES (substring(p_msg, 1, 400));
$$ LANGUAGE sql;

CREATE FUNCTION pkg_demo.open_emps(p_deptno INT)
RETURNS TABLE (empno INT, ename VARCHAR, sal NUMERIC) AS $$
   SELECT e.empno, e.ename, e.sal FROM emp e
     WHERE e.deptno = p_deptno ORDER BY e.empno;
$$ LANGUAGE sql;

CREATE FUNCTION trg_emp_audit_fn() RETURNS trigger AS $$
BEGIN
   INSERT INTO t_audit(table_name, action) VALUES ('EMP', TG_OP);
   RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_emp_audit
AFTER INSERT OR UPDATE OR DELETE ON emp
FOR EACH ROW EXECUTE FUNCTION trg_emp_audit_fn();

INSERT INTO dept VALUES (10,'ACCOUNTING','NEW YORK'),(20,'RESEARCH','DALLAS'),
                        (30,'SALES','CHICAGO'),(40,'OPERATIONS','BOSTON');

INSERT INTO emp (empno, ename, job, mgr, hiredate, sal, comm, deptno) VALUES
 (7839,'KING','PRESIDENT',NULL,'1981-11-17',5000,NULL,10),
 (7698,'BLAKE','MANAGER',7839,'1981-05-01',2850,NULL,30),
 (7782,'CLARK','MANAGER',7839,'1981-06-09',2450,NULL,10),
 (7566,'JONES','MANAGER',7839,'1981-04-02',2975,NULL,20),
 (7788,'SCOTT','ANALYST',7566,'1987-04-19',3000,NULL,20),
 (7902,'FORD','ANALYST',7566,'1981-12-03',3000,NULL,20),
 (7369,'SMITH','CLERK',7902,'1980-12-17',800,NULL,20),
 (7499,'ALLEN','SALESMAN',7698,'1981-02-20',1600,300,30),
 (7521,'WARD','SALESMAN',7698,'1981-02-22',1250,500,30),
 (7654,'MARTIN','SALESMAN',7698,'1981-09-28',1250,1400,30),
 (7844,'TURNER','SALESMAN',7698,'1981-09-08',1500,0,30),
 (7900,'JAMES','CLERK',7698,'1981-12-03',950,NULL,30),
 (7934,'MILLER','CLERK',7782,'1982-01-23',1300,NULL,10);

INSERT INTO emp (empno, ename, job, mgr, hiredate, sal, deptno, notes)
VALUES (8001,'EMPTYTEST','CLERK',7698,CURRENT_DATE,900,20,'');

INSERT INTO t_types (n_small, n_full, n_dec, v_var, c_fixed, d_date, ts,
                     raw16, big_text, big_bin, i_day)
VALUES (127, 1234567890123, 123.45, 'ciao', 'AB',
        '2026-09-11', '2026-09-11 10:20:30.123456',
        decode('DEADBEEF01020304','hex'), rpad('x', 100, 'y'),
        decode('CAFE0011','hex'), INTERVAL '1 02:03:04.567' DAY TO SECOND(3));

INSERT INTO t_default_seq(tag) VALUES ('primo'), ('secondo');
"""


def main():
    conn = psycopg.connect(host=POSTGRES.host, port=POSTGRES.port,
                           dbname=POSTGRES.dbname, user=POSTGRES.user,
                           password=POSTGRES.password, autocommit=True)
    with conn.cursor() as cur:
        cur.execute(SCHEMA_SQL)
        cur.execute("SELECT count(*) FROM emp")
        n = cur.fetchone()[0]
        cur.execute("SELECT table_name FROM information_schema.tables "
                    "WHERE table_schema = 'public' ORDER BY 1")
        tables = [r[0] for r in cur.fetchall()]
    conn.close()
    print(f"PostgreSQL mirror pronto. emp={n} righe, tabelle: {', '.join(tables)}")


if __name__ == "__main__":
    main()
