#!/usr/bin/env python3
"""Setup schema di test su Oracle 26ai Free.

- Attende che il database sia raggiungibile (container in avvio)
- Crea/allinea l'utente TESTAPP (idempotente)
- Crea lo schema dimostrativo con le feature Oracle che il proxy
  OracleBridge dovra' tradurre: tipi, sequenze, viste, sinonimi,
  package, trigger, REF CURSOR, dati seed.

Uso: python3 setup_oracle.py
"""
import sys
import time
from pathlib import Path

import oracledb

sys.path.insert(0, str(Path(__file__).parent))
from config import ORACLE  # noqa: E402

WAIT_RETRIES = 240
WAIT_SECONDS = 5

DROP_OBJECTS = ["TRG_EMP_AUD", "PKG_DEMO", "F_SAL_LEVEL", "V_HIGH_SAL", "E",
                "T_DEFAULT_SEQ", "T_AUDIT", "T_LOG", "T_TYPES", "EMP", "DEPT",
                "SEQ_EMP", "SEQ_DEFAULT"]


def wait_for_db():
    print(f"Attendo Oracle su {ORACLE.dsn} ...")
    last_err = None
    for i in range(WAIT_RETRIES):
        try:
            with oracledb.connect(user="system", password=ORACLE.sys_password,
                                  dsn=ORACLE.dsn) as conn:
                v = conn.cursor().execute(
                    "select banner from v$version where rownum = 1").fetchone()
                print(f"DB pronto: {v[0]}")
                return
        except Exception as e:  # noqa: BLE001
            last_err = e
            if (i + 1) % 6 == 0:
                print(f"  ... ancora in attesa ({(i+1)*WAIT_SECONDS}s): "
                      f"{type(e).__name__}")
            time.sleep(WAIT_SECONDS)
    raise SystemExit(f"Database non raggiungibile: {last_err}")


def ensure_user():
    with oracledb.connect(user="system", password=ORACLE.sys_password,
                          dsn=ORACLE.dsn) as conn:
        exists = ex(conn,
            "select count(*) from dba_users where username = 'TESTAPP'"
        ).fetchone()[0]
        if not exists:
            print("Creo utente TESTAPP ...")
            ex(conn, 'create user testapp identified by "TestApp_26ai"')
        else:
            ex(conn, 'alter user testapp identified by "TestApp_26ai"')
        for g in ["grant connect, resource to testapp",
                  "grant unlimited tablespace to testapp",
                  "grant create view, create synonym, create sequence to testapp"]:
            try:
                ex(conn, g)
            except oracledb.DatabaseError as e:
                if "ORA-01919" not in str(e):  # ruolo inesistente
                    raise
        conn.commit()
        print("Utente TESTAPP pronto.")


# ---------------------------------------------------------------------------
# Schema di test: lista esplicita di statement (niente parsing: robusto con
# blocchi PL/SQL contenenti CASE...END, loop, ecc.)
# ---------------------------------------------------------------------------
STMTS = [
    ("tab.dept", """CREATE TABLE dept (
       deptno  NUMBER(2)    CONSTRAINT pk_dept PRIMARY KEY,
       dname   VARCHAR2(14) NOT NULL,
       loc     VARCHAR2(13))"""),

    ("tab.emp", """CREATE TABLE emp (
       empno    NUMBER(4)    CONSTRAINT pk_emp PRIMARY KEY,
       ename    VARCHAR2(10) NOT NULL,
       job      VARCHAR2(9),
       mgr      NUMBER(4) REFERENCES emp(empno),
       hiredate DATE         DEFAULT SYSDATE NOT NULL,
       sal      NUMBER(7,2),
       comm     NUMBER(7,2),
       deptno   NUMBER(2) REFERENCES dept(deptno),
       notes    CLOB,
       foto     BLOB)"""),

    ("idx.emp", """CREATE INDEX idx_emp_ename ON emp(ename)"""),
    ("idx.emp.sal", """CREATE INDEX idx_emp_sal ON emp(sal)"""),
    ("idx.emp.upper", """CREATE INDEX idx_emp_upper ON emp(UPPER(ename))"""),

    ("tab.t_types", """CREATE TABLE t_types (
       id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
       n_small  NUMBER(3),
       n_full   NUMBER,
       n_dec    NUMBER(9,2),
       v_var    VARCHAR2(50),
       c_fixed  CHAR(5),
       d_date   DATE,
       ts       TIMESTAMP(6),
       raw16    RAW(16),
       big_text CLOB,
       big_bin  BLOB,
       i_day    INTERVAL DAY(2) TO SECOND(3))"""),

    ("tab.t_log", """CREATE TABLE t_log (
       id  NUMBER GENERATED ALWAYS AS IDENTITY,
       ts  TIMESTAMP DEFAULT SYSTIMESTAMP,
       msg VARCHAR2(400))"""),

    ("tab.t_audit", """CREATE TABLE t_audit (
       table_name VARCHAR2(30),
       action     VARCHAR2(10),
       cnt        NUMBER DEFAULT 1,
       ts         DATE DEFAULT SYSDATE)"""),

    ("seq.emp", """CREATE SEQUENCE seq_emp START WITH 1000 INCREMENT BY 10"""),
    ("seq.default", """CREATE SEQUENCE seq_default START WITH 1"""),

    ("tab.t_default_seq", """CREATE TABLE t_default_seq (
       id  NUMBER DEFAULT seq_default.NEXTVAL PRIMARY KEY,
       tag VARCHAR2(30))"""),

    ("view.high_sal", """CREATE VIEW v_high_sal AS
       SELECT empno, ename, sal FROM emp WHERE sal >= 2500"""),
    ("syn.e", """CREATE SYNONYM e FOR emp"""),

    ("fn.f_sal_level", """CREATE FUNCTION f_sal_level(p_sal NUMBER) RETURN VARCHAR2 IS
BEGIN
   RETURN CASE WHEN p_sal >= 3000 THEN 'HIGH'
               WHEN p_sal >= 1500 THEN 'MID'
               ELSE 'LOW' END;
END;"""),

    ("pkg.spec", """CREATE OR REPLACE PACKAGE pkg_demo AS
   g_session_val NUMBER := 0;
   PROCEDURE set_x(p_val NUMBER);
   FUNCTION  get_x RETURN NUMBER;
   FUNCTION  get_emp_name(p_empno NUMBER) RETURN VARCHAR2;
   PROCEDURE log_msg(p_msg VARCHAR2);
   TYPE ref_cur IS REF CURSOR;
   PROCEDURE open_emps(p_deptno NUMBER, p_cur OUT ref_cur);
END pkg_demo;"""),

    ("pkg.body", """CREATE OR REPLACE PACKAGE BODY pkg_demo AS
   PROCEDURE set_x(p_val NUMBER) IS
   BEGIN
      g_session_val := p_val;
   END;

   FUNCTION get_x RETURN NUMBER IS
   BEGIN
      RETURN g_session_val;
   END;

   FUNCTION get_emp_name(p_empno NUMBER) RETURN VARCHAR2 IS
      l_name emp.ename%TYPE;
   BEGIN
      SELECT ename INTO l_name FROM emp WHERE empno = p_empno;
      RETURN l_name;
   EXCEPTION
      WHEN NO_DATA_FOUND THEN RETURN NULL;
   END;

   PROCEDURE log_msg(p_msg VARCHAR2) IS
   BEGIN
      INSERT INTO t_log(msg) VALUES (substr(p_msg, 1, 400));
      COMMIT;
   END;

   PROCEDURE open_emps(p_deptno NUMBER, p_cur OUT ref_cur) IS
   BEGIN
      OPEN p_cur FOR SELECT empno, ename, sal FROM emp
                      WHERE deptno = p_deptno ORDER BY empno;
   END;
END pkg_demo;"""),

    ("trg.emp_audit", """CREATE OR REPLACE TRIGGER trg_emp_audit
AFTER INSERT OR UPDATE OR DELETE ON emp
FOR EACH ROW
DECLARE
   l_action VARCHAR2(10);
BEGIN
   l_action := CASE WHEN INSERTING THEN 'INSERT'
                    WHEN UPDATING  THEN 'UPDATE'
                    ELSE 'DELETE' END;
   INSERT INTO t_audit(table_name, action) VALUES ('EMP', l_action);
END;"""),

    # ---------------- seed ----------------
    ("seed.dept", """INSERT ALL
   INTO dept VALUES (10,'ACCOUNTING','NEW YORK')
   INTO dept VALUES (20,'RESEARCH','DALLAS')
   INTO dept VALUES (30,'SALES','CHICAGO')
   INTO dept VALUES (40,'OPERATIONS','BOSTON')
   SELECT 1 FROM dual"""),

    ("seed.emp", """INSERT ALL
   INTO emp (empno, ename, job, mgr, hiredate, sal, comm, deptno)
        VALUES (7839,'KING','PRESIDENT',NULL,TO_DATE('17-11-1981','DD-MM-YYYY'),5000,NULL,10)
   INTO emp (empno, ename, job, mgr, hiredate, sal, comm, deptno)
        VALUES (7698,'BLAKE','MANAGER',7839,TO_DATE('01-05-1981','DD-MM-YYYY'),2850,NULL,30)
   INTO emp (empno, ename, job, mgr, hiredate, sal, comm, deptno)
        VALUES (7782,'CLARK','MANAGER',7839,TO_DATE('09-06-1981','DD-MM-YYYY'),2450,NULL,10)
   INTO emp (empno, ename, job, mgr, hiredate, sal, comm, deptno)
        VALUES (7566,'JONES','MANAGER',7839,TO_DATE('02-04-1981','DD-MM-YYYY'),2975,NULL,20)
   INTO emp (empno, ename, job, mgr, hiredate, sal, comm, deptno)
        VALUES (7788,'SCOTT','ANALYST',7566,TO_DATE('19-04-1987','DD-MM-YYYY'),3000,NULL,20)
   INTO emp (empno, ename, job, mgr, hiredate, sal, comm, deptno)
        VALUES (7902,'FORD','ANALYST',7566,TO_DATE('03-12-1981','DD-MM-YYYY'),3000,NULL,20)
   INTO emp (empno, ename, job, mgr, hiredate, sal, comm, deptno)
        VALUES (7369,'SMITH','CLERK',7902,TO_DATE('17-12-1980','DD-MM-YYYY'),800,NULL,20)
   INTO emp (empno, ename, job, mgr, hiredate, sal, comm, deptno)
        VALUES (7499,'ALLEN','SALESMAN',7698,TO_DATE('20-02-1981','DD-MM-YYYY'),1600,300,30)
   INTO emp (empno, ename, job, mgr, hiredate, sal, comm, deptno)
        VALUES (7521,'WARD','SALESMAN',7698,TO_DATE('22-02-1981','DD-MM-YYYY'),1250,500,30)
   INTO emp (empno, ename, job, mgr, hiredate, sal, comm, deptno)
        VALUES (7654,'MARTIN','SALESMAN',7698,TO_DATE('28-09-1981','DD-MM-YYYY'),1250,1400,30)
   INTO emp (empno, ename, job, mgr, hiredate, sal, comm, deptno)
        VALUES (7844,'TURNER','SALESMAN',7698,TO_DATE('08-09-1981','DD-MM-YYYY'),1500,0,30)
   INTO emp (empno, ename, job, mgr, hiredate, sal, comm, deptno)
        VALUES (7900,'JAMES','CLERK',7698,TO_DATE('03-12-1981','DD-MM-YYYY'),950,NULL,30)
   INTO emp (empno, ename, job, mgr, hiredate, sal, comm, deptno)
        VALUES (7934,'MILLER','CLERK',7782,TO_DATE('23-01-1982','DD-MM-YYYY'),1300,NULL,10)
   SELECT 1 FROM dual"""),

    ("seed.empty", """INSERT INTO emp (empno, ename, job, mgr, hiredate, sal, deptno, notes)
   VALUES (8001,'EMPTYTEST','CLERK',7698,SYSDATE,900,20,'')"""),

    ("seed.t_types", """INSERT INTO t_types
       (n_small, n_full, n_dec, v_var, c_fixed, d_date, ts, raw16,
        big_text, big_bin, i_day)
     VALUES (127, 1234567890123, 123.45, 'ciao', 'AB',
             DATE '2026-09-11', TIMESTAMP '2026-09-11 10:20:30.123456',
             HEXTORAW('DEADBEEF01020304'), RPAD('x', 100, 'y'),
             HEXTORAW('CAFE' || '00' || '11'),
             INTERVAL '1 02:03:04.567' DAY TO SECOND(3))"""),

    ("seed.t_default_seq", "INSERT INTO t_default_seq(tag) VALUES ('primo')"),
    ("seed.t_default_seq2", "INSERT INTO t_default_seq(tag) VALUES ('secondo')"),
]


def ex(conn, sql):
    c = conn.cursor()
    c.execute(sql)
    return c  # il chiamante puo' fare .fetchone()


def drop_existing(conn):
    rows = ex(conn,
        "select object_name, object_type from user_objects "
        "where object_name in (" + ",".join(f"'{o}'" for o in DROP_OBJECTS) + ")"
    ).fetchall()
    order = {"TRIGGER": 0, "INDEX": 1, "PACKAGE BODY": 2, "PACKAGE": 2,
             "PROCEDURE": 3, "FUNCTION": 3, "SYNONYM": 4, "VIEW": 4,
             "SEQUENCE": 5, "TABLE": 6}
    dropped = set()
    for name, otype in sorted(rows, key=lambda r: order.get(r[1], 9)):
        key = (name, otype)
        if key in dropped:
            continue
        dropped.add(key)
        if otype == "PACKAGE BODY":
            continue  # cade col PACKAGE
        if otype == "TABLE":
            sql = f'DROP TABLE {name} CASCADE CONSTRAINTS PURGE'
        elif otype == "INDEX":
            continue  # cadono con le tabelle
        else:
            sql = f'DROP {otype} {name}'
        ex(conn, sql)
    if rows:
        print(f"Rimosso schema precedente ({len(dropped)} oggetti).")


def main():
    wait_for_db()
    ensure_user()
    with oracledb.connect(user=ORACLE.user, password=ORACLE.password,
                          dsn=ORACLE.dsn) as conn:
        print("Creo schema di test ...")
        drop_existing(conn)
        conn.commit()
        errors = 0
        for label, sql in STMTS:
            try:
                ex(conn, sql)
            except oracledb.DatabaseError as e:
                errors += 1
                print(f"  ERRORE [{label}]: {str(e).splitlines()[0]}")
        conn.commit()
        n_emp = conn.cursor().execute("select count(*) from emp").fetchone()[0]
        objs = conn.cursor().execute(
            "select object_type, count(*) from user_objects "
            "group by object_type order by 1").fetchall()
        print("Oggetti:", ", ".join(f"{t}={n}" for t, n in objs))
        print(f"emp: {n_emp} righe | errori: {errors}")
        if errors:
            raise SystemExit(1)


if __name__ == "__main__":
    main()
